# Generated by debtap
# Maintainer: vanta
# Contributor: vanta
pkgname=vanta
pkgver=2.11.0
pkgrel=1
pkgdesc="Vanta security tool for Linux."
arch=('x86_64')
url="https://vanta.com"
backup=('etc/vanta.conf')
options=('!strip' '!emptydirs')
source_x86_64=("https://app.vanta.com/osquery/download/linux")
sha512sums_x86_64=('SKIP')

package(){
    if [ -d "data" ]; then rm -Rf ./data; fi
	mkdir -p data
	tar xzf data.tar.gz -C data
	ls -l data/var/vanta
	ls -l data/etc

	install -Dm644 data/var/vanta/cert.pem "$pkgdir"/var/$pkgname/cert.pem
	install -Dm755 data/var/vanta/launcher "$pkgdir"/var/$pkgname/launcher
	install -Dm755 data/var/vanta/metalauncher "$pkgdir"/var/$pkgname/metalauncher
	install -Dm755 data/var/vanta/osqueryd "$pkgdir"/var/$pkgname/osqueryd
	install -Dm755 data/var/vanta/osquery-vanta.ext "$pkgdir"/var/$pkgname/osquery-vanta.ext
	install -Dm755 data/var/vanta/vanta-cli "$pkgdir"/var/$pkgname/vanta-cli

	install -Dm644 data/etc/vanta.conf "$pkgdir"/etc/vanta.conf

	install -Dm644 data/usr/lib/systemd/system/vanta.service "$pkgdir"/usr/lib/systemd/system/vanta.service
}

post_install() {
	echo "Configure your KEY and OWNER_EMAIL in /etc/vanta.conf."
}
